In [0]:
#All important imports
import requests, bs4
import re as reg
import pandas as pd

#our first function
#This function extracts and store the data of 1st and 2nd shift students
def first_second():
  #we are going store all these info
  total_theory = []
  sessional = []
  total_practical = []
  names = []
  percentage = []
  enrollment_no = []
  roll_no = []
  t_back = []
  roll  = range(10, 150)
  
  for i in roll:
    if i <=99:
      re = requests.get('http://result.bteupexam.in/year/result.aspx?Roll_no=E16120330000' + str(i))
      #we just need .printtext class data
      soup = bs4.BeautifulSoup(re.text, 'lxml')
      marks = soup.select('.printtext')
      
    else:
      re = requests.get('http://result.bteupexam.in/year/result.aspx?Roll_no=E1612033000' + str(i))
      soup = bs4.BeautifulSoup(re.text, 'lxml')
      #we just need .printtext class data
      marks = soup.select('.printtext')
#To understand all of these loop thing and marks[i]
#please visit the website and explore source code
#and don't forget to see marks variable
#You would understand everything
    if len(marks) == 0:
      continue 
      
    #here I am comparing this text because, 
    #These is a bug website and It is showing the result of Failed students also.
    #and we don't want this
      
    elif marks[3].text != '\xa0 [930] [ELECTRONICS ENGINEERING] 05 Semster \r\n                                ':
      continue
    
    else:
      #Here we are taking the name of student
      raw_na = marks[4].text
      
      #Need to clean the names of student
      if reg.search(r"([A-Z])+(\s)([A-Z]+)(\s)([A-Z]+)", raw_na):
        na = reg.search(r"([A-Z])+(\s)([A-Z]+)(\s)([A-Z]+)", raw_na)
        names.append(na.group())
                
      elif  reg.search(r"([A-Z]+(\s)([A-Z]+))", raw_na):
        na = reg.search(r"([A-Z]+(\s)([A-Z]+))", raw_na)
        names.append(na.group())
      
      elif reg.search(r"([A-Z]+)", raw_na):
        na = reg.search(r"([A-Z]+)", raw_na)
        names.append(na.group())
             
      #Here we are taking the enrollment number of student
      raw_enro = marks[6].text
      enro = reg.search(r"(E)([0-9]+)", raw_enro)
      enrollment_no.append(enro.group())

      #Here we are finding the sum of numbers to calculate percentage
      #ts is total possible numbers
      ts = 0
      for i in range(10, 65, 5):
        ts += int(marks[i].text)
      #gs is how much student got
      gs = 0
      for i in range(12, 67, 5):
        gs += int(marks[i].text)
      
      #some simple math to cal percentage
      percentage.append(round((gs/ts) * 100, 2))
      
      #Total number in theory
      total_theory.append(gs)
      
      #here we are taking Total number in sessionals
      sessional.append(int(marks[52].text))
      
      #here we are taking Total number in practical     
      tp = 0
      for i in range(32, 52, 5): 
        tp += int(marks[i].text)
        
      total_practical.append(tp)
      
      #here we are taking names of back subjects
      #this could be a bit complicated to understand
      back = []
      for i in range(12, 27, 5):
        get_m = int(marks[i].text)
        if get_m < 17:
          back.append(marks[i-3].text)
      if len(back) == 0:
        a = []
      else:
        a = back[:]

      t_back.append(a)

  return (names, enrollment_no, percentage, t_back, total_theory, sessional, total_practical)

   
#This function is extracting data of K group students
#I could think to add this fucntion into our first function
#But let it be

#Here we are doing the same stuff which we did in our first function
def k_group():
  total_theory = []
  sessional = []
  total_practical = []
  names = []
  percentage = []
  enrollment_no = []
  roll_no = []
  t_back = []
  roll  = range(0, 20)
  
  for i in roll:
    re = requests.get('http://result.bteupexam.in/year/result.aspx?Roll_no=E171203800000' + str(i))
    soup = bs4.BeautifulSoup(re.text, 'lxml')
    marks = soup.select('.printtext')
      

    if len(marks) == 0:
      continue 
    
    else:
      raw_na = marks[4].text
      
      if reg.search(r"([A-Z])+(\s)([A-Z]+)(\s)([A-Z]+)", raw_na):
        na = reg.search(r"([A-Z])+(\s)([A-Z]+)(\s)([A-Z]+)", raw_na)
        names.append(na.group())
                
      elif  reg.search(r"([A-Z]+(\s)([A-Z]+))", raw_na):
        na = reg.search(r"([A-Z]+(\s)([A-Z]+))", raw_na)
        names.append(na.group())
      
      elif reg.search(r"([A-Z]+)", raw_na):
        na = reg.search(r"([A-Z]+)", raw_na)
        names.append(na.group())
             
      raw_enro = marks[6].text
      enro = reg.search(r"(E)([0-9]+)", raw_enro)
      enrollment_no.append(enro.group())

       #It finds the sum of  numbers
      ts = 0
      for i in range(10, 65, 5):
        ts += int(marks[i].text)
      
      gs = 0
      for i in range(12, 67, 5):
        gs += int(marks[i].text)
      
      
      percentage.append(round((gs/ts) * 100, 2))
      
      #Total number in theory
      total_theory.append(gs)
      
      #Total number in sessionals
      sessional.append(int(marks[52].text))
      
      #Total number in practical     
      tp = 0
      for i in range(32, 52, 5): 
        tp += int(marks[i].text)
        
      total_practical.append(tp)
      

      back = []
      for i in range(12, 27, 5):
        get_m = int(marks[i].text)
        if get_m < 17:
          back.append(marks[i-3].text)
      if len(back) == 0:
        a = []
      else:
        a = back[:]

      t_back.append(a)

  return (names, enrollment_no, percentage, t_back, total_theory, sessional, total_practical)

In [0]:
#It is time to call of these fucntion 
names, enrollment_no, percentage, no_back, theory, sessional, practical = first_second()
#make a dataframe using these values
dataframe = {"Enrollment":enrollment_no, "Name":names, "Total of Theory":theory, "Sessional":sessional, "Total of Practicals":practical, "Percentage":percentage, "Back":no_back}
df = pd.DataFrame(dataframe) 
#Here we are just additing one more column in our dataset
#NO_of_backs
a = [len(i) for i in df.Back]
df['NO_of_backs'] = pd.Series(a)

names_k, enrollment_no_k, percentage_k, no_back_k, theory_k, sessional_k, practical_k  = k_group()
dataframe_k = {"Enrollment":enrollment_no_k, "Name":names_k, "Total of Theory":theory_k, "Sessional":sessional_k, "Total of Practicals":practical_k, "Percentage":percentage_k, "Back":no_back_k}
dfk = pd.DataFrame(dataframe_k)       
a = [len(i) for i in dfk.Back]
dfk['NO_of_backs'] = pd.Series(a)

In [4]:
#Let's add our two datasets to make one single dataset
df1 = df.append(dfk, ignore_index = True, sort = False)

#dfc = df1.copy()
#objs = [dfc, pd.DataFrame(dfc['Back'].tolist())]
#dfc = pd.concat(objs, axis=1).drop('Back', axis=1)
df1.head()

       Enrollment              Name  ...                         Back  NO_of_backs
0  E1612033000011   RAJ KUMAR SINGH  ...  [AUDIO & VIDEO ENGINEERING]            1
1  E1612033000012      MUKESH KUMAR  ...                           []            0
2  E1612033000014            NIKHIL  ...                           []            0
3  E1612033000015  PREM DUTT SHARMA  ...                           []            0
4  E1612033000016        KM SACHCHI  ...                           []            0

[5 rows x 8 columns]

In [0]:
#Now we can do many amazing things with this dataset